#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate embedded language packs C++ file from JSON language pack files.

This script reads all language pack JSON files from sys/language_packs/ and
generates sys/i18n_embedded_packs.cpp with embedded language pack data.

Usage:
    python generate_embedded_packs.py

The generated file contains all language pack JSON content as C++ string constants,
allowing the executable to run standalone without requiring external language files.
"""

import json
import os
import sys
from pathlib import Path

# Language pack directory
LANG_PACK_DIR = Path(__file__).parent / "language_packs"
OUTPUT_FILE = Path(__file__).parent / "i18n_embedded_packs.cpp"
LANGUAGES_JSON = LANG_PACK_DIR / "languages.json"

def get_language_list():
    """Get list of languages to embed from languages.json"""
    if not LANGUAGES_JSON.exists():
        print(f"Warning: {LANGUAGES_JSON} not found, scanning directory...")
        return []
    
    try:
        with open(LANGUAGES_JSON, 'r', encoding='utf-8') as f:
            data = json.load(f)
            return data.get('languages', [])
    except Exception as e:
        print(f"Error reading {LANGUAGES_JSON}: {e}")
        return []

def sanitize_identifier(lang_code):
    """Convert language code to valid C++ identifier"""
    return lang_code.replace('-', '_').replace('.', '_')


def generate_embedded_packs():
    """Generate the embedded language packs C++ file"""
    
    # Get language list
    languages = get_language_list()
    
    if not languages:
        print(f"Warning: No languages found, scanning {LANG_PACK_DIR} directory...")
        # Fallback: scan directory
        for json_file in LANG_PACK_DIR.glob("*.json"):
            if json_file.name != "languages.json":
                lang_code = json_file.stem
                languages.append({
                    "code": lang_code,
                    "name": lang_code,
                    "file": json_file.name
                })
    
    if not languages:
        print("Error: No language packs found!")
        sys.exit(1)
    
    print(f"Found {len(languages)} language packs")
    
    # Generate file content
    lines = []
    lines.append('/* i18n_embedded_packs.cpp')
    lines.append(' *')
    lines.append(' * Copyright (C) 2025 Praat i18n Implementation - Embedded Language Packs')
    lines.append(' *')
    lines.append(' * This file is AUTO-GENERATED by generate_embedded_packs.py')
    lines.append(' * DO NOT EDIT MANUALLY - regenerate using the Python script instead')
    lines.append(' *')
    lines.append(' * Contains all builtin language pack data embedded as string constants.')
    lines.append(' * This allows the exe to run standalone without requiring sys/language_packs directory.')
    lines.append(' */')
    lines.append('')
    lines.append('#include "i18n_embedded_packs.h"')
    lines.append('#include <map>')
    lines.append('#include <string>')
    lines.append('')
    lines.append('// Embedded language pack data')
    
    # Generate embedded constants for each language
    embedded_map_entries = []
    
    for lang in languages:
        lang_code = lang['code']
        lang_file = lang.get('file', f"{lang_code}.json")
        json_path = LANG_PACK_DIR / lang_file
        
        if not json_path.exists():
            print(f"Warning: {json_path} not found, skipping {lang_code}")
            continue
        
        print(f"Processing {lang_code} from {lang_file}...")
        
        # Read JSON content
        try:
            # Try to read with utf-8-sig first (handles BOM), fallback to utf-8
            try:
                with open(json_path, 'r', encoding='utf-8-sig') as f:
                    json_content = f.read()
            except:
                with open(json_path, 'r', encoding='utf-8') as f:
                    json_content = f.read()
            
            # Validate JSON
            try:
                json.loads(json_content)
            except json.JSONDecodeError as e:
                print(f"Error: Invalid JSON in {json_path}: {e}")
                continue
            
            # Generate constant name
            const_name = f"EMBEDDED_{sanitize_identifier(lang_code)}"
            delimiter = f"LANG_PACK_{sanitize_identifier(lang_code)}"
            
            # Write constant
            lines.append(f'static const char* {const_name} = R"{delimiter}({json_content}){delimiter}";')
            lines.append('')
            
            # Add to map
            embedded_map_entries.append(f'    {{"{lang_code}", {const_name}}}')
            
        except Exception as e:
            print(f"Error processing {lang_code}: {e}")
            continue
    
    # Generate map
    lines.append('// Map to lookup embedded packs')
    lines.append('static std::map<std::string, const char*> embeddedPacks = {')
    lines.append(',\n'.join(embedded_map_entries))
    lines.append('};')
    lines.append('')
    
    # Generate functions
    lines.append('std::string getEmbeddedLanguagePack(const std::string& languageCode) {')
    lines.append('    auto it = embeddedPacks.find(languageCode);')
    lines.append('    if (it != embeddedPacks.end()) {')
    lines.append('        return std::string(it->second);')
    lines.append('    }')
    lines.append('    return std::string();  // Return empty if not found')
    lines.append('}')
    lines.append('')
    
    lines.append('bool isLanguagePackEmbedded(const std::string& languageCode) {')
    lines.append('    return embeddedPacks.find(languageCode) != embeddedPacks.end();')
    lines.append('}')
    
    # Write file
    output_content = '\n'.join(lines)
    
    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(output_content)
        print(f"\nSuccessfully generated {OUTPUT_FILE}")
        print(f"Total size: {len(output_content)} bytes")
    except Exception as e:
        print(f"Error writing {OUTPUT_FILE}: {e}")
        sys.exit(1)

if __name__ == "__main__":
    generate_embedded_packs()

