/* i18n_embedded_packs.h
 *
 * Copyright (C) 2025 Praat i18n Implementation - Embedded Language Packs
 *
 * This file is AUTO-GENERATED by generate_embedded_packs.py
 * DO NOT EDIT MANUALLY - regenerate using the Python script instead
 *
 * Header for embedded language pack data.
 */

#ifndef _i18n_embedded_packs_h_
#define _i18n_embedded_packs_h_

#include <string>

// Get embedded language pack content
std::string getEmbeddedLanguagePack(const std::string& languageCode);

// Check if a language pack is embedded
bool isLanguagePackEmbedded(const std::string& languageCode);

#endif /* _i18n_embedded_packs_h_ */

