#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import re

def comprehensive_translate_german():
    """全面翻译德语语言包"""
    
    # 读取英语文件
    with open('en-US.json', 'r', encoding='utf-8-sig') as f:
        en_data = json.load(f)
    
    # 读取德语文件
    with open('de-DE.json', 'r', encoding='utf-8-sig') as f:
        de_data = json.load(f)
    
    # 需要保留英文的键
    keep_english = {
        'menu.help', 'menu.save_as_text_file', 'menu.write_to_text_file', 
        'menu.save_as_short_text_file', 'menu.write_to_short_text_file', 
        'menu.save_as_binary_file', 'menu.write_to_binary_file'
    }
    
    # 翻译规则
    def translate_text(text, context=""):
        """根据上下文翻译文本"""
        if not text or text in keep_english:
            return text
            
        # 基本翻译映射
        basic_translations = {
            # 基本词汇
            "New": "Neu",
            "Open": "Öffnen", 
            "Save": "Speichern",
            "Close": "Schließen",
            "Quit": "Beenden",
            "Edit": "Bearbeiten",
            "View": "Ansicht",
            "Window": "Fenster",
            "File": "Datei",
            "Tools": "Werkzeuge",
            "Help": "Hilfe",
            "About": "Über",
            "Settings": "Einstellungen",
            "Preferences": "Einstellungen",
            "Language": "Sprache",
            "Current": "Aktuell",
            "Cut": "Ausschneiden",
            "Copy": "Kopieren",
            "Paste": "Einfügen",
            "Delete": "Löschen",
            "Select": "Auswählen",
            "All": "Alle",
            "None": "Keine",
            "Find": "Suchen",
            "Replace": "Ersetzen",
            "Search": "Suchen",
            "Run": "Ausführen",
            "Convert": "Konvertieren",
            "Create": "Erstellen",
            "Add": "Hinzufügen",
            "Remove": "Entfernen",
            "Insert": "Einfügen",
            "Update": "Aktualisieren",
            "Change": "Ändern",
            "Modify": "Modifizieren",
            "Show": "Anzeigen",
            "Hide": "Ausblenden",
            "Draw": "Zeichnen",
            "Play": "Abspielen",
            "Stop": "Stoppen",
            "Pause": "Pausieren",
            "Record": "Aufnehmen",
            "Load": "Laden",
            "Write": "Schreiben",
            "Read": "Lesen",
            "Print": "Drucken",
            "Export": "Exportieren",
            "Import": "Importieren",
            "Format": "Formatieren",
            "Style": "Stil",
            "Color": "Farbe",
            "Colour": "Farbe",
            "Size": "Größe",
            "Width": "Breite",
            "Height": "Höhe",
            "Length": "Länge",
            "Time": "Zeit",
            "Duration": "Dauer",
            "Frequency": "Frequenz",
            "Amplitude": "Amplitude",
            "Intensity": "Intensität",
            "Pitch": "Tonhöhe",
            "Formant": "Formant",
            "Spectrum": "Spektrum",
            "Sound": "Ton",
            "Audio": "Audio",
            "Video": "Video",
            "Image": "Bild",
            "Picture": "Bild",
            "Text": "Text",
            "String": "Zeichenkette",
            "Number": "Zahl",
            "Value": "Wert",
            "Data": "Daten",
            "List": "Liste",
            "Table": "Tabelle",
            "Matrix": "Matrix",
            "Vector": "Vektor",
            "Point": "Punkt",
            "Line": "Linie",
            "Circle": "Kreis",
            "Rectangle": "Rechteck",
            "Square": "Quadrat",
            "Triangle": "Dreieck",
            "Arc": "Bogen",
            "Curve": "Kurve",
            "Graph": "Graph",
            "Chart": "Diagramm",
            "Plot": "Plot",
            "Axis": "Achse",
            "Axes": "Achsen",
            "Scale": "Skala",
            "Range": "Bereich",
            "Minimum": "Minimum",
            "Maximum": "Maximum",
            "Average": "Durchschnitt",
            "Mean": "Mittelwert",
            "Median": "Median",
            "Mode": "Modus",
            "Standard": "Standard",
            "Default": "Standard",
            "Custom": "Benutzerdefiniert",
            "User": "Benutzer",
            "System": "System",
            "Application": "Anwendung",
            "Program": "Programm",
            "Software": "Software",
            "Hardware": "Hardware",
            "Device": "Gerät",
            "Computer": "Computer",
            "Server": "Server",
            "Client": "Client",
            "Network": "Netzwerk",
            "Internet": "Internet",
            "Web": "Web",
            "Email": "E-Mail",
            "Message": "Nachricht",
            "Notification": "Benachrichtigung",
            "Alert": "Warnung",
            "Error": "Fehler",
            "Warning": "Warnung",
            "Info": "Info",
            "Information": "Information",
            "Details": "Details",
            "Summary": "Zusammenfassung",
            "Report": "Bericht",
            "Log": "Protokoll",
            "History": "Verlauf",
            "Backup": "Backup",
            "Restore": "Wiederherstellen",
            "Reset": "Zurücksetzen",
            "Clear": "Löschen",
            "Empty": "Leer",
            "Full": "Voll",
            "Complete": "Vollständig",
            "Partial": "Teilweise",
            "Incomplete": "Unvollständig",
            "Valid": "Gültig",
            "Invalid": "Ungültig",
            "Correct": "Korrekt",
            "Incorrect": "Inkorrekt",
            "True": "Wahr",
            "False": "Falsch",
            "Yes": "Ja",
            "No": "Nein",
            "OK": "OK",
            "Cancel": "Abbrechen",
            "Apply": "Anwenden",
            "Accept": "Akzeptieren",
            "Reject": "Ablehnen",
            "Confirm": "Bestätigen",
            "Deny": "Verweigern",
            "Allow": "Erlauben",
            "Block": "Blockieren",
            "Enable": "Aktivieren",
            "Disable": "Deaktivieren",
            "Start": "Start",
            "End": "Ende",
            "Begin": "Beginnen",
            "Finish": "Beenden",
            "Complete": "Vollenden",
            "Done": "Fertig",
            "Ready": "Bereit",
            "Busy": "Beschäftigt",
            "Available": "Verfügbar",
            "Unavailable": "Nicht verfügbar",
            "Online": "Online",
            "Offline": "Offline",
            "Active": "Aktiv",
            "Inactive": "Inaktiv",
            "Enabled": "Aktiviert",
            "Disabled": "Deaktiviert",
            "Visible": "Sichtbar",
            "Hidden": "Versteckt",
            "Public": "Öffentlich",
            "Private": "Privat",
            "Secure": "Sicher",
            "Unsecure": "Unsicher",
            "Safe": "Sicher",
            "Unsafe": "Unsicher",
            "Normal": "Normal",
            "Abnormal": "Abnormal",
            "Regular": "Regulär",
            "Irregular": "Irregulär",
            "Simple": "Einfach",
            "Complex": "Komplex",
            "Easy": "Einfach",
            "Difficult": "Schwierig",
            "Hard": "Schwer",
            "Soft": "Weich",
            "Fast": "Schnell",
            "Slow": "Langsam",
            "Quick": "Schnell",
            "Rapid": "Rapid",
            "Instant": "Sofort",
            "Immediate": "Sofortig",
            "Delayed": "Verzögert",
            "Late": "Spät",
            "Early": "Früh",
            "First": "Erste",
            "Last": "Letzte",
            "Next": "Nächste",
            "Previous": "Vorherige",
            "Before": "Vor",
            "After": "Nach",
            "Above": "Oben",
            "Below": "Unten",
            "Left": "Links",
            "Right": "Rechts",
            "Top": "Oben",
            "Bottom": "Unten",
            "Center": "Zentrum",
            "Middle": "Mitte",
            "Inside": "Innen",
            "Outside": "Außen",
            "Inner": "Innerer",
            "Outer": "Äußerer",
            "Upper": "Oberer",
            "Lower": "Unterer",
            "High": "Hoch",
            "Low": "Niedrig",
            "Big": "Groß",
            "Small": "Klein",
            "Large": "Groß",
            "Tiny": "Winzig",
            "Huge": "Riesig",
            "Long": "Lang",
            "Short": "Kurz",
            "Wide": "Breit",
            "Narrow": "Schmal",
            "Thick": "Dick",
            "Thin": "Dünn",
            "Deep": "Tief",
            "Shallow": "Flach",
            "Tall": "Hoch",
            "Short": "Kurz",
            "Old": "Alt",
            "New": "Neu",
            "Young": "Jung",
            "Fresh": "Frisch",
            "Stale": "Abgestanden",
            "Clean": "Sauber",
            "Dirty": "Schmutzig",
            "Clear": "Klar",
            "Blurry": "Verschwommen",
            "Sharp": "Scharf",
            "Dull": "Stumpf",
            "Bright": "Hell",
            "Dark": "Dunkel",
            "Light": "Hell",
            "Heavy": "Schwer",
            "Empty": "Leer",
            "Full": "Voll",
            "Open": "Offen",
            "Closed": "Geschlossen",
            "Locked": "Gesperrt",
            "Unlocked": "Entsperrt",
            "Free": "Frei",
            "Busy": "Beschäftigt",
            "Available": "Verfügbar",
            "Unavailable": "Nicht verfügbar",
            "Present": "Anwesend",
            "Absent": "Abwesend",
            "Here": "Hier",
            "There": "Dort",
            "Everywhere": "Überall",
            "Nowhere": "Nirgendwo",
            "Somewhere": "Irgendwo",
            "Anywhere": "Irgendwo",
            "Everywhere": "Überall",
            "Always": "Immer",
            "Never": "Niemals",
            "Sometimes": "Manchmal",
            "Often": "Oft",
            "Rarely": "Selten",
            "Usually": "Normalerweise",
            "Generally": "Allgemein",
            "Specifically": "Spezifisch",
            "Particularly": "Besonders",
            "Especially": "Besonders",
            "Mainly": "Hauptsächlich",
            "Mostly": "Meistens",
            "Partly": "Teilweise",
            "Completely": "Vollständig",
            "Totally": "Total",
            "Entirely": "Gänzlich",
            "Fully": "Vollständig",
            "Half": "Halb",
            "Quarter": "Viertel",
            "Third": "Drittel",
            "Double": "Doppelt",
            "Triple": "Dreifach",
            "Single": "Einzeln",
            "Multiple": "Mehrfach",
            "Many": "Viele",
            "Few": "Wenige",
            "Several": "Mehrere",
            "Some": "Einige",
            "Any": "Irgendein",
            "All": "Alle",
            "None": "Keine",
            "Nothing": "Nichts",
            "Something": "Etwas",
            "Everything": "Alles",
            "Anything": "Irgendetwas",
            "Someone": "Jemand",
            "Anyone": "Irgendjemand",
            "Everyone": "Jeder",
            "Nobody": "Niemand",
            "Somebody": "Jemand",
            "Anybody": "Irgendjemand",
            "Everybody": "Jeder",
            "This": "Dies",
            "That": "Das",
            "These": "Diese",
            "Those": "Jene",
            "Here": "Hier",
            "There": "Dort",
            "Where": "Wo",
            "When": "Wann",
            "Why": "Warum",
            "How": "Wie",
            "What": "Was",
            "Who": "Wer",
            "Which": "Welche",
            "Whose": "Wessen",
            "Whom": "Wen",
            "Whose": "Wessen",
            "Mine": "Mein",
            "Yours": "Dein",
            "His": "Sein",
            "Hers": "Ihr",
            "Ours": "Unser",
            "Theirs": "Ihr",
            "My": "Mein",
            "Your": "Dein",
            "His": "Sein",
            "Her": "Ihr",
            "Our": "Unser",
            "Their": "Ihr",
            "Me": "Mich",
            "You": "Du",
            "Him": "Ihn",
            "Her": "Ihr",
            "Us": "Uns",
            "Them": "Sie",
            "I": "Ich",
            "He": "Er",
            "She": "Sie",
            "It": "Es",
            "We": "Wir",
            "They": "Sie",
            "Am": "Bin",
            "Is": "Ist",
            "Are": "Sind",
            "Was": "War",
            "Were": "Waren",
            "Be": "Sein",
            "Been": "Gewesen",
            "Being": "Seiend",
            "Have": "Haben",
            "Has": "Hat",
            "Had": "Hatte",
            "Having": "Haben",
            "Do": "Tun",
            "Does": "Tut",
            "Did": "Tat",
            "Done": "Getan",
            "Doing": "Tuend",
            "Will": "Wird",
            "Would": "Würde",
            "Could": "Könnte",
            "Should": "Sollte",
            "May": "Kann",
            "Might": "Könnte",
            "Must": "Muss",
            "Can": "Kann",
            "Cannot": "Kann nicht",
            "Can't": "Kann nicht",
            "Won't": "Wird nicht",
            "Wouldn't": "Würde nicht",
            "Couldn't": "Könnte nicht",
            "Shouldn't": "Sollte nicht",
            "Mayn't": "Kann nicht",
            "Mightn't": "Könnte nicht",
            "Mustn't": "Muss nicht",
            "Shan't": "Wird nicht",
            "Needn't": "Braucht nicht",
            "Daren't": "Wagt nicht",
            "Oughtn't": "Sollte nicht",
            "Usedn't": "Gebrauchte nicht",
            "Hadn't": "Hatte nicht",
            "Haven't": "Habe nicht",
            "Hasn't": "Hat nicht",
            "Didn't": "Tat nicht",
            "Don't": "Tue nicht",
            "Doesn't": "Tut nicht",
            "Isn't": "Ist nicht",
            "Aren't": "Sind nicht",
            "Wasn't": "War nicht",
            "Weren't": "Waren nicht",
            "I'm": "Ich bin",
            "You're": "Du bist",
            "He's": "Er ist",
            "She's": "Sie ist",
            "It's": "Es ist",
            "We're": "Wir sind",
            "They're": "Sie sind",
            "I've": "Ich habe",
            "You've": "Du hast",
            "He's": "Er hat",
            "She's": "Sie hat",
            "It's": "Es hat",
            "We've": "Wir haben",
            "They've": "Sie haben",
            "I'll": "Ich werde",
            "You'll": "Du wirst",
            "He'll": "Er wird",
            "She'll": "Sie wird",
            "It'll": "Es wird",
            "We'll": "Wir werden",
            "They'll": "Sie werden",
            "I'd": "Ich würde",
            "You'd": "Du würdest",
            "He'd": "Er würde",
            "She'd": "Sie würde",
            "It'd": "Es würde",
            "We'd": "Wir würden",
            "They'd": "Sie würden",
            "I'm": "Ich bin",
            "You're": "Du bist",
            "He's": "Er ist",
            "She's": "Sie ist",
            "It's": "Es ist",
            "We're": "Wir sind",
            "They're": "Sie sind",
            "I've": "Ich habe",
            "You've": "Du hast",
            "He's": "Er hat",
            "She's": "Sie hat",
            "It's": "Es hat",
            "We've": "Wir haben",
            "They've": "Sie haben",
            "I'll": "Ich werde",
            "You'll": "Du wirst",
            "He'll": "Er wird",
            "She'll": "Sie wird",
            "It'll": "Es wird",
            "We'll": "Wir werden",
            "They'll": "Sie werden",
            "I'd": "Ich würde",
            "You'd": "Du würdest",
            "He'd": "Er würde",
            "She'd": "Sie würde",
            "It'd": "Es würde",
            "We'd": "Wir würden",
            "They'd": "Sie würden",
        }
        
        # 应用基本翻译
        result = text
        for en, de in basic_translations.items():
            if result == en:
                return de
            elif result.startswith(en + " "):
                return de + " " + result[len(en)+1:]
            elif result.endswith(" " + en):
                return result[:-len(en)-1] + " " + de
            elif " " + en + " " in result:
                return result.replace(" " + en + " ", " " + de + " ")
        
        # 处理特殊模式
        if result.startswith("-- ") and result.endswith(" --"):
            # 分隔符
            content = result[3:-3]
            if content in basic_translations:
                return "-- " + basic_translations[content] + " --"
        
        if result.endswith("..."):
            # 带省略号的菜单项
            base = result[:-3]
            if base in basic_translations:
                return basic_translations[base] + "..."
        
        if result.endswith(":"):
            # 带冒号的标签
            base = result[:-1]
            if base in basic_translations:
                return basic_translations[base] + ":"
        
        return result
    
    # 应用翻译
    updated_count = 0
    for key in en_data:
        if key in de_data and key not in keep_english:
            en_value = en_data[key]
            de_value = de_data[key]
            
            # 如果德语值和英语值相同，进行翻译
            if en_value == de_value:
                translation = translate_text(en_value, key)
                if translation != en_value:
                    de_data[key] = translation
                    updated_count += 1
    
    # 保存文件
    with open('de-DE.json', 'w', encoding='utf-8') as f:
        json.dump(de_data, f, ensure_ascii=False, indent=2)
    
    print(f"已更新 {updated_count} 个条目")

if __name__ == "__main__":
    comprehensive_translate_german()
